---
baseURL: "/"
title: Best Kayak To Buy
paginate: 5
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: Best Kayak To Buy
  description: ExampleSite description
  keywords:
  - Blog
  - Portfolio
  - PaperMod
  author: Me
  images:
  - "<link or path of image for opengraph, twitter-cards>"
  DateFormat: January 2, 2006
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"
  label:
    text: Home
    icon: "/apple-touch-icon.png"
    iconHeight: 35
  profileMode:
    enabled: false
    title: ExampleSite
    subtitle: This is subtitle
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
    - name: Posts
      url: posts
    - name: Tags
      url: tags
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog
  socialIcons:
  - name: twitter
    url: https://twitter.com/
  - name: stackoverflow
    url: https://stackoverflow.com
  - name: github
    url: https://github.com/
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  editPost:
    URL: https://github.com/<path_to_repo>/content
    Text: Suggest Changes
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
    - title
    - permalink
    - summary
    - content
menu:
  main:
  - url: "/privacy-policy"
    name: Privacy Policy
    weight: 4
  - url: "/tag/buying-guides"
    name: Buying Guides
    weight: 3
  - url: https://cricutmachinesexpert.com
    name: Home
    weight: 1
  - url: "/affiliate-disclaimer/"
    name: Affiliate Disclaimer
    weight: 5
    identifier: tags
  - url: "/categories/"
    name: Brands
    weight: 2
    identifier: categories
